# fly.toml app configuration file generated for client-wispy-glade-6899 on 2025-08-24T14:16:12+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'client-wispy-glade-6899'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
