# fly.toml app configuration file generated for server-still-snow-4380 on 2025-08-24T14:22:49+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-still-snow-4380'
primary_region = 'syd'

[build]

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
